Repository TeamPhotoSurfer/PhotoSurfer-iOS, pull requests merged in 2022-07, with the labels that each got.

#4 [#2] 기초 프로젝트 세팅_폴더링
  PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/project.pbxproj
  PhotoSurfer-iOS/PhotoSurfer-iOS/Base.lproj/Main.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/Color.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Gifs/File.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Storyboards/Base.lproj/LaunchScreen.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Application/AppDelegate.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Application/SceneDelegate.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Const.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Extensions/UIColor+.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Protocols/EmptyDelegate.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Alarm.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/AlarmViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/Base.lproj/Main.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/MainTabBarController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Home.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/HomeViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/Setting.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/SettingViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Tag.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/TagViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/APIConstants.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Network/NetworkResult.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/ViewController.swift
Labels: ☁ sky, ✅ Chore

#9 [#8] 컬러 및 폰트 에셋 추가
  PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/project.pbxproj
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaGray95A10.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaGray95A30.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaGray95A70.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaOceanA60.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaOceanA75.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaWhiteA10.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaWhiteA30.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/alphaWhiteA70.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayBlack.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray10.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray20.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray30.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray40.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray5.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray50.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray60.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray70.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray80.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray90.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayGray950.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/grayWhite.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointBlue.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointGreen.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointMain.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointRed.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointSub.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Colors/Colors.xcassets/pointYellow.colorset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Extensions/UIColor+.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Extensions/UIFont+.swift
Labels: 🐑 정연, ✨ Pull Request

#12 [#7] 홈 에셋 제외한 UI
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Home.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/HomeViewController.swift
Labels: 🌊 혜수, ✨ Pull Request

#14 [#13] 검색뷰 서치바 및 컬렉션뷰 추가
  PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/project.pbxproj
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Identifier.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Storyboard.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/ViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Home.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/HomeViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Views/HomeSearch.storyboard
Labels: 🌊 혜수, ✨ Pull Request

#15 [#5] share extension 뷰 태그 일부 구현
  PhotoSurfer-iOS/ImageShareExtension/Extensions/UIColor+.swift
  PhotoSurfer-iOS/ImageShareExtension/Extensions/UIFont+.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Controllers/ShareViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Base.lproj/MainInterface.storyboard
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagCollectionViewCell.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagCollectionViewCell.xib
  PhotoSurfer-iOS/ImageShareExtension/ShareViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/project.pbxproj
Labels: ☁ sky, ✨ Pull Request

#17 [#16] share extension 태그 검색 기능 구현
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Controllers/ShareViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Base.lproj/MainInterface.storyboard
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagCollectionViewCell.xib
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagsHeaderCollectionReusableView.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagsHeaderCollectionReusableView.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/project.pbxproj
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Application/AppDelegate.swift
Labels: ☁ sky, ✨ Pull Request

#21 Style/#10 tag UI kite
  PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/project.pbxproj
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonGray50.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonGray50.imageset/icPlusLineButtonGray50.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonGray50.imageset/icPlusLineButtonGray50@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonGray50.imageset/icPlusLineButtonGray50@3x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonMain.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonMain.imageset/icPlusLineButtonMain.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonMain.imageset/icPlusLineButtonMain@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonMain.imageset/icPlusLineButtonMain@3x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonWhite.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonWhite.imageset/icPlusLineButtonWhite.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonWhite.imageset/icPlusLineButtonWhite@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icPlusLineButtonWhite.imageset/icPlusLineButtonWhite@3x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Identifier.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Image.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Storyboard.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/ViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Tag.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/TagViewController.swift
Labels: 🐑 정연, ✨ Pull Request

#27 [#25] 태그탭 UI 변경사항에 맞게 수정
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/TagViewController.swift
Labels: 🐑 정연, ✨ Pull Request

#30 [#28] 홈 에셋 추가
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/hyesu.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/hyesu.imageset/hyesu.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/hyesu.imageset/hyesu@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/hyesu.imageset/hyesu@3x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/imgSea.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/imgSea.imageset/imgSea.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/imgSea.imageset/imgSea@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/imgSea.imageset/imgSea@3x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Home.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/HomeViewController.swift
Labels: 🌊 혜수, ✨ Pull Request

#32 [#29] share extension 검색 입력 기능 구현 중 프로젝트 세팅 변경
  PhotoSurfer-iOS/ImageShareExtension/Extensions/UIViewController+.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Controllers/ShareViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Base.lproj/MainInterface.storyboard
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagCollectionViewCell.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagCollectionViewCell.xib
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagsHeaderCollectionReusableView.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagsHeaderCollectionReusableView.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/project.pbxproj
Labels: ☁ sky, ✅ Chore, ✨ Pull Request

#34 Style/#31 search header hs
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Identifier.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Controllers/HomeViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Views/HomeSearchHeaderCollectionReusableView.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Views/HomeSearchHeaderCollectionReusableView.xib
Labels: 🌊 혜수, ✨ Pull Request

#36 [#35] 검색결과 UI
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Identifier.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Image.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard
Labels: 🌊 혜수, ✨ Pull Request

#41 [#40] 앱 아이콘 추가
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/100.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/1024.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/114.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/120.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/144.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/152.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/167.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/180.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/20.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/29.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/40.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/50.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/57.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/58.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/60.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/72.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/76.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/80.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/87.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🌊 혜수, ✨ Pull Request

#38 [#33] 환경 설정 UI
  PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/xcshareddata/xcschemes/ImageShareExtension.xcscheme
  PhotoSurfer-iOS/PhotoSurfer-iOS.xcodeproj/xcshareddata/xcschemes/PhotoSurfer-iOS.xcscheme
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/rightBackIconButton.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/rightBackIconButton.imageset/rightBackIconButton.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/rightBackIconButton.imageset/rightBackIconButton@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/rightBackIconButton.imageset/rightBackIconButton@3x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Image.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Storyboard.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/ViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/Setting.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/SettingPolicy.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/SettingPolicyViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/SettingUser.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/SettingUserViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/SettingViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/TagViewController.swift
Labels: 🐑 정연, ✨ Pull Request

#39 [#29] share extension 태그 검색 UI
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Controllers/ShareViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Base.lproj/MainInterface.storyboard
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagCollectionViewCell.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagCollectionViewCell.xib
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagsHeaderCollectionReusableView.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Views/Cells/TagsHeaderCollectionReusableView.xib
Labels: ☁ sky, ✨ Pull Request

#43 [#37] Picture
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icMenuVertical.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icMenuVertical.imageset/icMenuVertical.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icMenuVertical.imageset/icMenuVertical@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/icMenuVertical.imageset/icMenuVertical@3x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/imgDummy.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/imgDummy.imageset/스크린샷 2022-07-17 오전 11.04.56-3.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/imgDummy.imageset/스크린샷 2022-07-17 오전 11.04.56-4.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/imgDummy.imageset/스크린샷 2022-07-17 오전 11.04.56.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard
Labels: 🌊 혜수, ✨ Pull Request

#50 [#47] alarm main hs
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/imgAlarm.imageset/img_alarm.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/imgAlarm.imageset/img_alarm@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/imgAlarm.imageset/img_alarm@3x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Controllers/AlarmViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Controllers/AlarmViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Views/Alarm.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Views/AlarmListSectionHeaderView.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/TableViewCells/AlarmListTableViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/TableViewCells/AlarmListTableViewCell.xib
Labels: 🌊 혜수, ✨ Pull Request

#59 [#58] alarm/select UI구현
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/rightShareIconButton.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/rightShareIconButton.imageset/rightShareIconButton.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/rightShareIconButton.imageset/rightShareIconButton@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/rightShareIconButton.imageset/rightShareIconButton@3x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Storyboard.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/ViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Controllers/AlarmViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard
Labels: 🌊 혜수, ✨ Pull Request

#65 [#62] tab bar UI 구현
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/selectAlarm.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/selectSearch.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/selectSetting.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/selectTag.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Views/Alarm.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/Base.lproj/Main.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Views/Home.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/Setting.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Views/Tag.storyboard
Labels: ☁ sky, ✨ Pull Request

#66 [#63] alarm detail UI
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/bellLine.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/bellLine.imageset/bellLine.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/bellLine.imageset/bellLine@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/bellLine.imageset/bellLine@3x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmDetail/Controllers/AlarmDetailViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmDetail/Views/AlarmDetail.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard
Labels: 🌊 혜수, ✨ Pull Request

#68 [#67] asset image Slice width 값 수정
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Controllers/SetRepresentTagViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Views/Cells/RepresentTagTableViewCell.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/colorGray.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/colorMain.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/colorSub.imageset/Contents.json
Labels: ☁ sky, ✨ Pull Request

#69 [#57] 대표 태그, 알림 설정 기능 수정
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Controllers/SetAlarmViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Controllers/SetRepresentTagViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Controllers/ShareViewController+Extension.swift
Labels: ☁ sky, ✨ Pull Request

#71 [#70] tag type
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Controllers/HomeViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
Labels: 🌊 혜수, ✨ Pull Request

#73 [#56] share extension 태그검색뷰 오류 해결
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Controllers/ShareViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Views/Base.lproj/MainInterface.storyboard
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Views/Cells/TagCollectionViewCell.swift
Labels: ☁ sky, ✨ Pull Request

#74 [#72] view detail hs
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Controllers/HomeViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Controllers/HomeViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Views/HomeSearch.storyboard
Labels: 🌊 혜수, ✨ Pull Request

#77 [#75] 태그 검색 뷰 디자인 디테일
  PhotoSurfer-iOS/ImageShareExtension/Extensions/UIViewController+.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Controllers/SetAlarmViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Controllers/SetRepresentTagViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Controllers/SetRepresentTagViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Views/Cells/RepresentTagTableViewCell.xib
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Views/SetAlarm.storyboard
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Alarm/Views/SetRepresentTag.storyboard
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Controllers/ShareViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Views/Base.lproj/MainInterface.storyboard
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Views/Cells/TagCollectionViewCell.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Views/Cells/TagsHeaderCollectionReusableView.swift
  PhotoSurfer-iOS/ImageShareExtension/Presentation/Tag/Views/Cells/TagsHeaderCollectionReusableView.xib
Labels: ☁ sky, ☘️ Feat

#78 [#72] view detail hs
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard
Labels: 🌊 혜수, ✨ Pull Request

#79 [#76] lottie 구현
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Views/SetAlarm.storyboard
Labels: ☁ sky, ✨ Pull Request

#87 [#24] 오류 있는 태그 메뉴
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Extensions/UITextField+.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/Views/Setting.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Views/Tag.storyboard
Labels: 🐑 정연, ☘️ Feat

#88 [#86] 태그 검색 뷰 디테일 수정
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Views/Base.lproj/MainInterface.storyboard
Labels: ☁ sky, ✨ Pull Request

#90 [#72] view detail hs
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Extensions/UIViewController+.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard
Labels: 🌊 혜수, ✨ Pull Request

#92 [#91] get push server hs
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Controllers/AlarmViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Views/Alarm.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmList/Controllers/AlarmListViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmList/Controllers/AlarmListViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/TableViewCells/AlarmListTableViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/TableViewCells/AlarmListTableViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PushModel/PushResponse.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Network/NetworkConstant.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Network/URLConstant.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushRouter.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushService.swift
Labels: 🌊 혜수, ✨ Pull Request

#93 [#81] 태그탭 디테일
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Storyboard.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/ViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagDetailViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Views/Tag.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Views/TagDetail.storyboard
Labels: 🐑 정연, ✨ Pull Request

#96 [#94] 홈 자주 검색한 태그 연결
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Controllers/HomeViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Home/Controllers/HomeViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PushModel/PushResponse.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/TagModel/TagResponse.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Network/NetworkConstant.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/TagAPI/TagRouter.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/TagAPI/TagService.swift
Labels: 🌊 혜수, ✨ Pull Request

#98 [#97] 태그 중복 제어, 디자인 오류 수정
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift
Labels: ☁ sky, ✨ Pull Request

#100 [#99] 태그수정 UI detail
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
Labels: 🌊 혜수, ✨ Pull Request

#102 [#101] /tag/main
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift
Labels: 🌊 혜수, ✨ Pull Request

#107 [#106] 검색결과 서버연결
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PhotoModel/PhotoResponse.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoRouter.swift
Labels: 🌊 혜수, ✨ Pull Request

#109 [#82] 온보딩 UI 및 화면 연결
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Image.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/Storyboard.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Common/Consts/ViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Onboarding/Controller/OnboardingViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Onboarding/Views/Onboarding.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Splash/Controllers/SplashViewController.swift
Labels: 🐑 정연, ✨ Pull Request

#112 [#111] 알람 온보딩
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Onboarding/Controller/AlarmOnboardingViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Onboarding/Controller/OnboardingViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Onboarding/Views/AlarmOnboarding.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Onboarding/Views/Onboarding.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Views/Tag.storyboard
Labels: 🐑 정연, ☘️ Feat, 🍭 Style

#117 [#116] todayAPI 연결
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Controllers/AlarmViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Controllers/AlarmViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Views/Alarm.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PushModel/PushResponse.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushService.swift
Labels: 🌊 혜수, ✨ Pull Request

#118 [#95] tagMenu -> UIMenu
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
Labels: 🐑 정연, 🔨 Fix

#121 [#120] 검색 태그 삭제시 새로고침
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift
Labels: 🌊 혜수, ✨ Pull Request

#123 [#105] 태그탭 조회 API 연결
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/TagModel/TagResponse.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Network/NetworkBase.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/TagAPI/TagService.swift
Labels: 🐑 정연, ✨ Pull Request

#126 [#122] 알림상세 이동시 id값 전달
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Alarm/Controllers/AlarmViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmDetail/Controllers/AlarmDetailViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmDetail/Views/AlarmDetail.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmList/Controllers/AlarmListViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushRouter.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushService.swift
Labels: 🌊 혜수, ✨ Pull Request

#128 [#125] get tag detail
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagDetailViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
Labels: 🐑 정연, ✨ Pull Request

#129 [#104] 사진에 태그 추가 - post ~/photo
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetRepresentTagViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetRepresentTagViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Views/SetAlarm.storyboard
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Views/Base.lproj/MainInterface.storyboard
Labels: ☁ sky, ✨ Pull Request

#131 [#127] detail hs
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoRouter.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoService.swift
Labels: 🌊 혜수, ✨ Pull Request

#134 [#130] push response 수정
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/TableViewCells/AlarmListTableViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PushModel/PushResponse.swift
Labels: ☁ sky, ✨ Pull Request

#135 [#133] 알림 상세
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmDetail/Controllers/AlarmDetailViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmDetail/Views/AlarmDetail.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PushModel/PushResponse.swift
Labels: 🌊 혜수, ✨ Pull Request

#137 [#132] 태그 북마크 추가 API
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
Labels: 🐑 정연, ✨ Pull Request

#139 [#136] 검색 로직 오류 수정
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeSearch/Controllers/HomeSearchViewController.swift
Labels: 🌊 혜수, ✨ Pull Request

#141 [#138] Del tag mark
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
Labels: 🐑 정연, ☘️ Feat

#143 [#140] 태그 삭제 API 연결
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
Labels: 🐑 정연, ✨ Pull Request

#145 [#144] 태그 앨범 사진 상세 API 연결
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagDetailViewController.swift
Labels: 🐑 정연, ✨ Pull Request

#147 [#130] post - push/:photoid 알림설정 서버 연결
  PhotoSurfer-iOS/ImageShareExtension/Source/Extensions/UIViewController+.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PushModel/PushResponse.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushRouter.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PushAPI/PushService.swift
Labels: ☁ sky, ✨ Pull Request

#148 [#146] 온보딩 분기처리 수정
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Onboarding/Controller/OnboardingViewController.swift
Labels: 🐑 정연, ✨ Pull Request

#151 [#124] 태그탭 수정 기능 오류 수정 -> 앱잼 내 기능 삭제
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Login/Controllers/LoginViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
Labels: 🐑 정연, ✨ Pull Request

#152 [#130] 알림설정 예외 처리 추가
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift
Labels: ☁ sky, 🔨 Fix, ✨ Pull Request

#154 [#127] 사진에 태그 추가
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/PhotoModel/PhotoResponse.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoRouter.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoService.swift
Labels: 🌊 혜수, ✨ Pull Request

#155 [#153] 태그탭 레이아웃 수정
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
Labels: 🐑 정연, 🍭 Style

#156 [#150] 검색 뷰 오류 수정
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController.swift
Labels: ☁ sky, ✨ Pull Request

#157 [#127] 개별사진 태그수정
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Controllers/PictureViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Picture/Views/Picture.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoRouter.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/PhotoAPI/PhotoService.swift
Labels: 🌊 혜수, ✨ Pull Request

#158 [#45] 검색결과 다중선택
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/PhotoCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
Labels: 🌊 혜수, ✨ Pull Request

#161 [#159] multiselect tag UI
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard
Labels: 🌊 혜수, ✨ Pull Request

#163 [#153] 태그탭 UI 수정
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
Labels: 🐑 정연, 🍭 Style

#164 [#159] 다중사진 태그삭제
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
Labels: 🌊 혜수, ✨ Pull Request

#165 [#160] 뷰 에러 수정 및 키보드 로직 변경
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Views/SetAlarm.storyboard
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift
Labels: ☁ sky, ✨ Pull Request

#166 [#159] 다중선택 태그추가
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard
Labels: 🌊 혜수, ✨ Pull Request

#167 [#159] 다중선택 수정
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController+Extension.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
Labels: 🌊 혜수, ✨ Pull Request

#173 [#172] 온보딩 배경 에셋 추가
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/onboardingLeft.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/onboardingLeft.imageset/onboardingLeft.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/onboardingLeft.imageset/onboardingLeft@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/onboardingLeft.imageset/onboardingLeft@3x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/onboardingRight.imageset/Contents.json
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/onboardingRight.imageset/onboardingRight.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/onboardingRight.imageset/onboardingRight@2x.png
  PhotoSurfer-iOS/PhotoSurfer-iOS/Resource/Assets/Assets.xcassets/onboardingRight.imageset/onboardingRight@3x.png
  PhotoSurfer-iOS/Pods/Pods.xcodeproj/project.pbxproj
Labels: 🐑 정연, ✨ Pull Request

#176 [#162] 로그인 API 연결
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Login/Controllers/LoginViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/AuthModel/AuthRequest.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/Data/AuthModel/AuthResponse.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/AuthAPI/AuthRouter.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Service/NetworkAPI/AuthAPI/AuthService.swift
Labels: 🐑 정연, ✨ Pull Request

#177 [#160] extension error 수정
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetRepresentTagViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetRepresentTagViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/MainTabBarController.swift
Labels: ☁ sky, ✨ Pull Request

#181 [#179] layout 에러 수정
  PhotoSurfer-iOS/ImageShareExtension/Source/Extensions/UIViewController+.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Tag/Controllers/ShareViewController.swift
Labels: ☁ sky, ✨ Pull Request

#183 [#179] 저장 안되는 오류 수정
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController+Extension.swift
  PhotoSurfer-iOS/ImageShareExtension/Source/Presentation/Alarm/Controllers/SetAlarmViewController.swift
Labels: ☁ sky, ✨ Pull Request

#184 [#182] 자잘한 코드 정리
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/CollectionViewCells/TagAlbumCollectionViewCell.xib
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Onboarding/Controller/OnboardingViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Setting/Controllers/SettingUserViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Tag/Controllers/TagViewController.swift
Labels: 🐑 정연, ✨ Pull Request

#185 [#174] 뒤로가기, 선택 색상 수정
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Application/AppDelegate.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmList/Controllers/AlarmListViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/AlarmList/Views/AlarmList.storyboard
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/Common/TableViewCells/AlarmListTableViewCell.swift
Labels: 🌊 혜수, ✨ Pull Request

#186 [#174] 태그검색 엠티뷰 추가
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Controllers/HomeResultViewController.swift
  PhotoSurfer-iOS/PhotoSurfer-iOS/Source/Presentation/HomeResult/Views/HomeResult.storyboard
Labels: 🌊 혜수, ✨ Pull Request
